using Confluent.Kafka;
using Dapper;
using Microsoft.Data.SqlClient;
using System.Data;
using System.Text.Json;
using PokerTrack.Contracts;
using System.Net.Http.Json;

namespace PokerTrack.Worker;
//BackgroundService runs continuously alongside the web app as a hosted service.
//Consumes Debezium CDC events from Kafka and recomputes analytics after each added or deleted session
public class Worker(ILogger<Worker> logger, IConfiguration config, IHttpClientFactory httpClientFactory) : BackgroundService
{
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        var consumerConfig = new ConsumerConfig
        {
            BootstrapServers = config["Kafka:BootstrapServers"],
            GroupId = config["Kafka:ConsumerGroup"],

            //Only processes new messages going forward
            AutoOffsetReset = AutoOffsetReset.Latest,
            //Only advance commits after fully successful processing
            EnableAutoCommit = false
        };

        using var consumer = new ConsumerBuilder<string, string>(consumerConfig).Build();
        logger.LogInformation("Kafka consumer created, connecting to {Servers}", config["Kafka:BootstrapServers"]);
        // Topic name is generated by Debezium: {prefix}.{database}.{schema}.{table}
        consumer.Subscribe("poker.PokerTrack.dbo.Sessions");

        logger.LogInformation("Worker started, listening for session events...");

        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                var result = consumer.Consume(TimeSpan.FromSeconds(5));
                if (result is null)
                {
                    logger.LogInformation("No messages received, waiting...");
                    continue;
                }

                if (result.Message.Value is null)
                {
                    consumer.Commit(result);
                    continue;
                }
                //if message exists we parse payload
                var envelope = JsonDocument.Parse(result.Message.Value);
                var payload = envelope.RootElement.GetProperty("payload");
                var op = payload.GetProperty("op").GetString();

                //get the userId from before if op is delete,d, and the after if op is anything else: c,u,r
                string? userId = null;
                
                if (op == "d")
                {
                    // Delete — read userId from "before"
                    var before = payload.GetProperty("before");
                    userId = before.GetProperty("UserId").GetString();
                }
                else if (op is "c" or "u" or "r")
                {
                    var after = payload.GetProperty("after");
                    userId = after.GetProperty("UserId").GetString();
                }

                if (userId is null)
                {
                    consumer.Commit(result);
                    continue;
                }

                logger.LogInformation("Processing session event op={Op} for user={UserId}", op, userId);
                
                await UpdateAnalyticsAsync(userId);
                consumer.Commit(result);
            }
            catch (OperationCanceledException)
            {
                break;
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Error processing Kafka message");
                await Task.Delay(5000, stoppingToken);
            }
        }

        consumer.Close();
    }

    private async Task UpdateAnalyticsAsync(string userId)
    {
        var connectionString = config.GetConnectionString("Sql");
        using IDbConnection db = new SqlConnection(connectionString);

        var sessions = (await db.QueryAsync<PokerSession>(
            "SELECT * FROM Sessions WHERE UserId = @UserId",
            new { UserId = userId })).ToList();

        if (sessions.Count == 0) return;

        var profits = sessions.Select(s => s.Profit).ToList();
        var winning = profits.Count(p => p > 0);
        var losing = profits.Count(p => p < 0);
        var totalProfit = profits.Sum();
        var avgProfit = profits.Average();
        var avgHourly = sessions.Average(s => s.HourlyRate);
        var biggestWin = profits.Max();
        var biggestLoss = profits.Min();
        var winRate = sessions.Count > 0 ? (decimal)winning / sessions.Count : 0;

        // Calculate current streak
        var ordered = sessions.OrderByDescending(s => s.SessionDate).ToList();
        int streak = 0;
        bool? streakPositive = null;
        foreach (var s in ordered)
        {
            if (streakPositive is null)
            {
                streakPositive = s.Profit >= 0;
                streak = s.Profit >= 0 ? 1 : -1;
            }
            else if (streakPositive == s.Profit >= 0)
            {
                streak += s.Profit >= 0 ? 1 : -1;
            }
            else break;
        }

        // Longest win streak
        int longestWin = 0, current = 0;
        foreach (var s in sessions.OrderBy(s => s.SessionDate))
        {
            current = s.Profit >= 0 ? current + 1 : 0;
            if (current > longestWin) longestWin = current;
        }

        const string upsert = """
            MERGE Analytics AS target
            USING (SELECT @UserId AS UserId) AS source ON target.UserId = source.UserId
            WHEN MATCHED THEN UPDATE SET
                TotalSessions       = @TotalSessions,
                TotalProfit         = @TotalProfit,
                AvgProfitPerSession = @AvgProfitPerSession,
                AvgHourlyRate       = @AvgHourlyRate,
                WinningSessions     = @WinningSessions,
                LosingSessions      = @LosingSessions,
                WinRate             = @WinRate,
                CurrentStreak       = @CurrentStreak,
                LongestWinStreak    = @LongestWinStreak,
                BiggestWin          = @BiggestWin,
                BiggestLoss         = @BiggestLoss,
                LastUpdated         = GETUTCDATE()
            WHEN NOT MATCHED THEN INSERT
                (UserId, TotalSessions, TotalProfit, AvgProfitPerSession, AvgHourlyRate,
                 WinningSessions, LosingSessions, WinRate, CurrentStreak, LongestWinStreak,
                 BiggestWin, BiggestLoss, LastUpdated)
            VALUES
                (@UserId, @TotalSessions, @TotalProfit, @AvgProfitPerSession, @AvgHourlyRate,
                 @WinningSessions, @LosingSessions, @WinRate, @CurrentStreak, @LongestWinStreak,
                 @BiggestWin, @BiggestLoss, GETUTCDATE());
            """;
        // Notify the web app that analytics are ready. 
        await db.ExecuteAsync(upsert, new
        {
            UserId = userId,
            TotalSessions = sessions.Count,
            TotalProfit = totalProfit,
            AvgProfitPerSession = avgProfit,
            AvgHourlyRate = avgHourly,
            WinningSessions = winning,
            LosingSessions = losing,
            WinRate = winRate,
            CurrentStreak = streak,
            LongestWinStreak = longestWin,
            BiggestWin = biggestWin,
            BiggestLoss = biggestLoss
        });

        logger.LogInformation("Analytics updated for user={UserId}", userId);

        // Notify browser via SignalR
        try
        {
            var client = httpClientFactory.CreateClient();
            await client.PostAsJsonAsync("http://localhost:5211/internal/analytics-updated", userId);
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "Could not notify web app of analytics update");
        }
    }
}