using Confluent.Kafka;
using Dapper;
using Microsoft.Data.SqlClient;
using System.Data;
using System.Text.Json;
using System.Net.Http.Json;
using PokerTrack.Contracts;
using Serilog.Context;

namespace PokerTrack.Worker;

// BackgroundService runs continuously alongside the web app as a hosted service.
// Consumes Debezium CDC events from Kafka and recomputes analytics after each change.
public class Worker(ILogger<Worker> logger, IConfiguration config, IHttpClientFactory httpClientFactory) : BackgroundService
{
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        var consumerConfig = new ConsumerConfig
        {
            BootstrapServers = config["Kafka:BootstrapServers"] ?? "localhost:9092",
            GroupId = config["Kafka:ConsumerGroup"] ?? "pokertrack-worker",
            // Only processes new messages going forward
            AutoOffsetReset = AutoOffsetReset.Latest,
            // Only advance commits after fully successful processing
            EnableAutoCommit = false
        };

        using var consumer = new ConsumerBuilder<string, string>(consumerConfig).Build();
        logger.LogInformation("Kafka consumer created, connecting to {Servers}", config["Kafka:BootstrapServers"]);

        // Topic name is generated by Debezium: {prefix}.{database}.{schema}.{table}
        consumer.Subscribe("poker.PokerTrack.dbo.Sessions");
        logger.LogInformation("Worker started, listening for session events...");

        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                var result = consumer.Consume(TimeSpan.FromSeconds(5));
                if (result is null)
                {
                    logger.LogInformation("No messages received, waiting...");
                    continue;
                }

                // Null value is a Debezium tombstone — signals a deleted record in the log.
                // Commit and skip since the delete is handled via op=d below.
                if (result.Message.Value is null)
                {
                    consumer.Commit(result);
                    continue;
                }

                var envelope = JsonDocument.Parse(result.Message.Value);
                var payload = envelope.RootElement.GetProperty("payload");
                var op = payload.GetProperty("op").GetString();

                // Generate a unique correlation ID for this event.
                // Every log line inside the using block automatically includes it.
                var correlationId = Guid.NewGuid().ToString("N")[..12];

                using (LogContext.PushProperty("CorrelationId", correlationId))
                using (LogContext.PushProperty("Op", op))
                {
                    string? userId = null;

                    if (op == "d")
                    {
                        // On deletes "after" is null — userId must be read from "before"
                        var before = payload.GetProperty("before");
                        userId = before.GetProperty("UserId").GetString();
                    }
                    else if (op is "c" or "u" or "r")
                    {
                        // c=insert, u=update, r=snapshot read on connector startup
                        var after = payload.GetProperty("after");
                        userId = after.GetProperty("UserId").GetString();
                    }

                    if (userId is null)
                    {
                        consumer.Commit(result);
                        continue;
                    }

                    logger.LogInformation("Processing session event op={Op} for user={UserId}", op, userId);

                    await UpdateAnalyticsAsync(userId, correlationId);
                    consumer.Commit(result);
                }
            }
            catch (OperationCanceledException)
            {
                break;
            }
            catch (Exception ex)
            {
                // Log and wait before retrying to avoid hammering a broken connection
                logger.LogError(ex, "Error processing Kafka message");
                await Task.Delay(5000, stoppingToken);
            }
        }

        consumer.Close();
    }

    private async Task UpdateAnalyticsAsync(string userId, string correlationId)
    {
        // Push correlation ID into log context so all log lines in this method
        // are traceable back to the same Kafka event
        using (LogContext.PushProperty("CorrelationId", correlationId))
        {
            var connectionString = config.GetConnectionString("Sql");
            using IDbConnection db = new SqlConnection(connectionString);

            // Pull all sessions for this user and recompute analytics from scratch.
            // Simple and accurate — avoids incremental update edge cases.
            // This makes processing idempotent — if a message is redelivered and processed
            // twice, the result is identical because it's always derived from the
            // source of truth in the Sessions table.
            var sessions = (await db.QueryAsync<PokerSession>(
                "SELECT * FROM Sessions WHERE UserId = @UserId",
                new { UserId = userId })).ToList();

            if (sessions.Count == 0) return;

            var profits = sessions.Select(s => s.Profit).ToList();
            var winning = profits.Count(p => p > 0);
            var losing = profits.Count(p => p < 0);
            var totalProfit = profits.Sum();
            var avgProfit = profits.Average();
            var avgHourly = sessions.Average(s => s.HourlyRate);
            var biggestWin = profits.Max();
            var biggestLoss = profits.Min();
            var winRate = sessions.Count > 0 ? (decimal)winning / sessions.Count : 0;

            // Walk sessions newest-first, count consecutive wins or losses
            var ordered = sessions.OrderByDescending(s => s.SessionDate).ToList();
            int streak = 0;
            bool? streakPositive = null;
            foreach (var s in ordered)
            {
                if (streakPositive is null)
                {
                    streakPositive = s.Profit >= 0;
                    streak = s.Profit >= 0 ? 1 : -1;
                }
                else if (streakPositive == s.Profit >= 0)
                {
                    streak += s.Profit >= 0 ? 1 : -1;
                }
                else break;
            }

            // Walk sessions oldest-first to find the longest winning streak
            int longestWin = 0, current = 0;
            foreach (var s in sessions.OrderBy(s => s.SessionDate))
            {
                current = s.Profit >= 0 ? current + 1 : 0;
                if (current > longestWin) longestWin = current;
            }

            // MERGE handles both first-time insert and subsequent updates in one statement
            const string upsert = """
                MERGE Analytics AS target
                USING (SELECT @UserId AS UserId) AS source ON target.UserId = source.UserId
                WHEN MATCHED THEN UPDATE SET
                    TotalSessions       = @TotalSessions,
                    TotalProfit         = @TotalProfit,
                    AvgProfitPerSession = @AvgProfitPerSession,
                    AvgHourlyRate       = @AvgHourlyRate,
                    WinningSessions     = @WinningSessions,
                    LosingSessions      = @LosingSessions,
                    WinRate             = @WinRate,
                    CurrentStreak       = @CurrentStreak,
                    LongestWinStreak    = @LongestWinStreak,
                    BiggestWin          = @BiggestWin,
                    BiggestLoss         = @BiggestLoss,
                    LastUpdated         = GETUTCDATE()
                WHEN NOT MATCHED THEN INSERT
                    (UserId, TotalSessions, TotalProfit, AvgProfitPerSession, AvgHourlyRate,
                     WinningSessions, LosingSessions, WinRate, CurrentStreak, LongestWinStreak,
                     BiggestWin, BiggestLoss, LastUpdated)
                VALUES
                    (@UserId, @TotalSessions, @TotalProfit, @AvgProfitPerSession, @AvgHourlyRate,
                     @WinningSessions, @LosingSessions, @WinRate, @CurrentStreak, @LongestWinStreak,
                     @BiggestWin, @BiggestLoss, GETUTCDATE());
                """;

            await db.ExecuteAsync(upsert, new
            {
                UserId = userId,
                TotalSessions = sessions.Count,
                TotalProfit = totalProfit,
                AvgProfitPerSession = avgProfit,
                AvgHourlyRate = avgHourly,
                WinningSessions = winning,
                LosingSessions = losing,
                WinRate = winRate,
                CurrentStreak = streak,
                LongestWinStreak = longestWin,
                BiggestWin = biggestWin,
                BiggestLoss = biggestLoss
            });

            logger.LogInformation("Analytics updated for user={UserId}", userId);
            logger.LogInformation("User has logged {TotalSessions} total sessions.",sessions.Count);
            // Notify the web app via HTTP so it can push a SignalR message to the browser.
            // Wrapped in try/catch so a failed notification doesn't fail the Kafka commit.
            try
            {
                var client = httpClientFactory.CreateClient();
                await client.PostAsJsonAsync("http://localhost:5211/internal/analytics-updated", userId);
            }
            catch (Exception ex)
            {
                logger.LogWarning(ex, "Could not notify web app of analytics update");
            }
        }
    }
}